### ISSUE TITLE
metaclass conflict error

### ISSUE THREAD

**Issue by gaoyifan** [m13253/VxWireguard-Generator#3]
```
$ vwgen add xxx
Traceback (most recent call last):
  File "/opt/venv/vwgen/bin/vwgen", line 11, in <module>
    load_entry_point('VxWireguard-Generator==1.0', 'console_scripts', 'vwgen')()
  File "/opt/venv/vwgen/lib/python3.6/site-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/__main__.py", line 30, in __main__
  File "/opt/venv/vwgen/lib/python3.6/site-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/vwgen.py", line 38, in main
  File "/opt/venv/vwgen/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/venv/vwgen/lib/python3.6/site-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/vwgen_add.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/venv/vwgen/lib/python3.6/site-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/common.py", line 57, in <module>
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

This error occoured after commit eaf26fc50aefe47e608b3eead2d1a1b47573b4e8.

**Comment by m13253** [comment]
Thank you for your report.

Would you please try whether upgrading to Python 3.7 can solve the problem?

**Comment by gaoyifan** [comment]
Yes, upgrading to python 3.7 solved the problem. Thanks for your outstanding work!
